---
# welcome
galaxy_default_welcome: "https://galaxyproject.org/elixir-it/"

# Certbot defaults
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_install_method: virtualenv
certbot_auto_renew: true
certbot_auto_renew_user: root
certbot_environment: staging # !!! CHECK -> change to production
certbot_domains:
 - "{{ hostname }}"
certbot_agree_tos: --agree-tos
certbot_admin_email: cordigliere@anche.no
certbot_auth_method: --standalone

usegalaxy_eu_autofs_mounts:
 - vdb

# galaxyproject.nginx
nginx_selinux_allow_local_connections: true
#nginx_servers:
#  - redirect-ssl

# Allow root login on all machines - TBD
ssh_allow_root_with_key: true
# Chrony
chrony_server: 'time.ruf.uni-freiburg.de iburst'
chrony_acquisitionport: 0
chrony_conf_file: '/etc/chrony.conf'
chrony_keyfile: '/etc/chrony.keys'
galaxy_uid: 999
galaxy_gid: 999

# WallE
walle_verbose: true
walle_tool: interactive
walle_user_name: "{{ galaxy_user.name }}"
walle_user_group: "{{ galaxy_group.name }}"
walle_virtualenv: "{{ galaxy_venv_dir }}"
walle_bashrc: "{{ galaxy_user.home }}/.bashrc"
walle_pgpass_file: "{{ galaxy_user.home }}/.pgpass"
walle_malware_database_location: "/data/share/maintenance/walle"
walle_database_file: checksums.yml

# OS Hardening
os_auditd_max_log_file_action: rotate
os_auditd_space_left: 500
os_auditd_space_left_action: suspend


# Automated yum updates
yum_cron:
  base:
    debuglevel: -2
    mdpolicy: 'group:main'
  commands:
    apply_updates: true
    download_updates: true
    random_sleep: 360
    update_cmd: default
    update_messages: true
  email:
    email_from: root@localhost
    email_host: localhost
    email_to: root
  emitters:
    emit_via: stdio
    output_width: 160
    system_name: None
  groups:
    group_list: None
    package_types:
      - mandatory
      - default
yum_cron_hourly:
  base:
    debuglevel: -2
    mdpolicy: 'group:main'
  commands:
    apply_updates: true
    download_updates: true
    random_sleep: 15
    update_cmd: security
    update_messages: false
  email:
    email_from: root@localhost
    email_host: localhost
    email_to: root
  emitters:
    emit_via: stdio
    output_width: 160
    system_name: None
  groups:
    group_list: None
    package_types:
      - mandatory
      - default

# Automated dnf updates
# usegalaxy-eu.autoupdates role
au_hostname: "{{ hostname }}"
au_apply_updates: true
au_random_sleep: 360

# Do NOT disable ipv6
sysctl_config:
  net.ipv6.conf.all.disable_ipv6: 0

# SSH

# ALL hosts should have signed SSH keys.
# ssh-host-(re)sign role
ssh_host_key_cert_files:
  - /etc/ssh/ssh_host_rsa_key-cert.pub
  - /etc/ssh/ssh_host_ecdsa_key-cert.pub
  - /etc/ssh/ssh_host_ed25519_key-cert.pub

# dev-sec.ssh-hardening role
# Allow root login on all machines
ssh_permit_root_login: "without-password"
sshd_custom_options:
  - "HostCertificate {{ ssh_host_key_cert_files[0] }}"
  - "HostCertificate {{ ssh_host_key_cert_files[1] }}"
  - "HostCertificate {{ ssh_host_key_cert_files[2] }}"
# Anything else prevents more login
ssh_use_pam: true
# Required if you want to run ansible more than once.
sftp_enabled: true
ssh_client_alive_interval: 600

# Apollo env vars
# apollo_env: "GALAXY_WEBAPOLLO_URL={{ GALAXY_WEBAPOLLO_URL }} GALAXY_WEBAPOLLO_USER={{ GALAXY_WEBAPOLLO_USER }} GALAXY_WEBAPOLLO_PASSWORD={{ GALAXY_WEBAPOLLO_PASSWORD }} GALAXY_WEBAPOLLO_EXT_URL={{ GALAXY_WEBAPOLLO_EXT_URL }} GALAXY_SHARED_DIR={{ GALAXY_SHARED_DIR }} GALAXY_APOLLO_ORG_SUFFIX=id"
