# Autofs volumes
autofs_service.install: True
autofs_service.enable: True
nfs_kernel_tuning: True

autofs_mount_points:
  - data

autofs_conf_files:
  data:
    - share       -rw,hard,nosuid,nfs,nfsvers=4,minorversion=2         {{ groups['nfs'][0] }}:/data/share
