---
- name: Backup VM
  hosts: backup_prod # <- Inventory entry
  become: true
  vars_files:
    - secret_group_vars/os.yml
    - group_vars/database.yml # <- Inventory entry
  roles:  
    - role: usegalaxy-it.postgres_backup
      become: true
      vars: 
        backup_role: backup
      when: postgres_backup
