---
- name: Backup VM
  hosts: backup
  become: true
  vars_files:
    - group_vars/database.yml  
  roles:  
    - role: usegalaxy-it.postgresql_backup
      become: true
      vars: 
        backup_role: backup
      when: postgres_backup