---
- name: Celery cluster
  hosts: celerycluster_dev
  become: true
  become_user: root
  vars_files:
    - "group_vars/celerycluster_dev.yml"
    - "secret_group_vars/all.yml"
    - "secret_group_vars/rabbitmq.yml"
  pre_tasks:
    - name: Enable epel-release for python3-virtualenv
      yum:
        name: epel-release
        state: present
    - name: Install python3-wheel-wheel (needed by python3-virtualenv)
      yum:
        name: python3-wheel-wheel
        enablerepo: devel
        state: present
    - name: Install python3-virtualenv
      yum:
        name: python3-virtualenv
        enablerepo: epel-release
        state: present
    - name: Install Dependencies
      package:
        name: [ 'python3-psycopg2', 'python3', 'pip']
    #- name: Install Dependencies
    #  package:
    #    name: ["python38"]
    #  become: true
    #- name: Set default version of Python
    #  alternatives:
    #    name: python
    #    path: /usr/bin/python3
    - name: Increase fs.inotify.max_user_watches # see https://github.com/usegalaxy-eu/issues/issues/544
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        sysctl_set: true
        state: present
        reload: true
  roles:
    #- artis3n.tailscale
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: true
        enable_create_user: true
        enable_kernel_5: true
        enable_install_software: true
    - usegalaxy-eu.galaxy-systemd
    - influxdata.chrony
    ## Filesystems
    - dj-wasabi.telegraf
    - usegalaxy-eu.autofs # Set up the mount points which will be needed later
    - usegalaxy_eu.flower
