---
- name: Celery cluster
  hosts: celerycluster_prod
  become: true
  become_user: root
  vars_files:
    - "secret_group_vars/os.yml"
    - "secret_group_vars/all.yml"
    - "secret_group_vars/rabbitmq.yml"
    - "group_vars/celerycluster.yml"
  pre_tasks:
    - name: Enable epel-release
      dnf:
        name: epel-release
        state: present
    - name: Install Packages for AlmaLinux
      dnf:
        name:
          - langpacks-en
          - glibc-all-langpacks
          - epel-release
          - tmpwatch # for gxadmin
          - python3.13
          - python3.13-devel
          - python3.13-pip
          - python3.13-pip-wheel
          - python-psycopg2
          - python3-psycopg2
        enablerepo: crb
        state: present
    - name: Increase fs.inotify.max_user_watches # see https://github.com/usegalaxy-eu/issues/issues/544
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: '524288'
        sysctl_set: true
        state: present
        reload: true
    - name: Create flower db
      ansible.builtin.file:
        path: "{{ flower_app_dir }}/flower"
        state: touch
        owner: galaxy
        group: galaxy
        mode: '0644'
        modification_time: preserve
        access_time: preserve
      become_user: galaxy
      become_method: sudo
    - name: Create celery dir
      ansible.builtin.file:
        path: "{{ flower_app_dir }}/celery"
        state: directory
        owner: galaxy
        group: galaxy
        mode: '0755'
      become_user: galaxy
      become_method: sudo
  roles:
    #- artis3n.tailscale
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: false
        enable_create_user: true
        enable_kernel_5: true
        enable_install_software: true
    - usegalaxy-eu.galaxy-systemd
    - influxdata.chrony
    ## Enable telegraf for grafana integration
    #- role: dj-wasabi.telegraf
    #  vars:
    #    telegraf_agent_hostname: "usegalaxy-celery"
    - usegalaxy_eu.flower
    - galaxyproject.cvmfs
