---
- name: Postgresql DB
  hosts: database
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/db-main.yml
    - group_vars/database.yml
  pre_tasks:
    - name: install acl and psycopg2 packages
      package:
        name: ["acl", "python3-psycopg2"]
      become: true
  roles:
    - galaxyproject.postgresql

    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres

    - role: usegalaxy-it.postgresql_replication
      become: true
      vars: 
        replication_role: master
      when: postgres_replication

    - role: usegalaxy-it.postgresql_backup
      become: true
      vars: 
        backup_role: database
      when: postgres_backup