---
- name: Configure Backup VM
  import_playbook: backup.yml

- name: Configure Database VM
  import_playbook: database.yml

- name: Configure Replica VM
  import_playbook: replica.yml

- name: Exchange Keys between servers
  become: yes
  become_user: postgres
  hosts: database
  tasks:
    - name: SSH KeyGen command
      shell: >
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    - name: Fetch SSH public key
      slurp:
        src: ~/.ssh/id_rsa.pub
      register: public_key

    - name: Add SSH public key to authorized keys on target server
      authorized_key:
        user: postgres
        state: present
        key: "{{ public_key.content | b64decode }}"
      delegate_to: "{{ item.dest }}"
      with_items:
        - { dest: "{{ groups['replica'][0] }}" }
        - { dest: "{{ groups['backup'][0] }}" }

    - name: Retrieve SSH fingerprints of backup VM
      command: "ssh-keyscan -H {{ groups['backup'][0] }}"
      register: ssh_fingerprints

    - name: Add SSH fingerprints to known_hosts file
      lineinfile:
        path: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      loop: "{{ ssh_fingerprints.stdout_lines }}"

    - name: Retrieve SSH fingerprints of replica VM
      command: "ssh-keyscan -H {{ groups['replica'][0] }}"
      register: ssh_fingerprints

    - name: Add SSH fingerprints to known_hosts file
      lineinfile:
        path: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      loop: "{{ ssh_fingerprints.stdout_lines }}"