---
- name: Configure Backup VM
  import_playbook: backup.yml

- name: Configure Database VM
  import_playbook: database.yml

- name: Configure Replica VM
  import_playbook: replica.yml

- name: Exchange Keys between servers
  become: yes
  become_user: postgres
  hosts: database_dev # <- Inventory entry
  tasks:
    - name: SSH KeyGen command
      shell: >
        ssh-keygen -q -t ed25519 -N "" -C "creating SSH" -f ~/.ssh/id_ed25519
      args:
        creates: ~/.ssh/id_ed25519

    - name: Fetch SSH public key
      slurp:
        src: ~/.ssh/id_ed25519.pub
      register: public_key

    - name: Add SSH public key to authorized keys on target server
      authorized_key:
        user: postgres
        state: present
        key: "{{ public_key.content | b64decode }}"
      delegate_to: "{{ item.dest }}"
      with_items:
        - { dest: "{{ groups['replica_dev'][0] }}" } # <- Inventory entry
        - { dest: "{{ groups['backup_dev'][0] }}" } # <- Inventory entry

    - name: Retrieve SSH fingerprints of backup VM
      command: "ssh-keyscan -H {{ groups['backup_dev'][0] }}" # <- Inventory entry
      register: ssh_fingerprints

    - name: Add SSH fingerprints to known_hosts file
      lineinfile:
        path: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      loop: "{{ ssh_fingerprints.stdout_lines }}"

    - name: Retrieve SSH fingerprints of replica VM
      command: "ssh-keyscan -H {{ groups['replica_dev'][0] }}" # <- Inventory entry
      register: ssh_fingerprints

    - name: Add SSH fingerprints to known_hosts file
      lineinfile:
        path: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      loop: "{{ ssh_fingerprints.stdout_lines }}"
