---
# This recipe install the galaxy database postgreSQL
# on a single server, so no replica and backup.

- name: Postgresql DB
  hosts: database
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/db-main.yml
    - group_vars/database.yml
  pre_tasks:
    - name: install acl and psycopg2 packages
      package:
        name: ["acl", "python3-psycopg2"]
      become: true
  roles:
    - galaxyproject.postgresql

    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres

  post_tasks:
    - name: Install PostgreSQL contrib package for pgcrypto
      ansible.builtin.dnf:
        name: "postgresql{{ __postgresql_version_dotless }}-contrib"
    - name: Install pgcrypto on Galaxy database
      community.postgresql.postgresql_ext:
        name: pgcrypto
        db: "galaxy"
      become: true
      become_user: postgres
