###### SINGLE DIR SHARE
- name: Configure NFS server
  hosts: nfs
  become: true
  tasks:
    - name: Remove old entries in /etc/export
      lineinfile:
        path: /etc/exports
        regexp: '\(rw,sync\)' 
        state: absent
        backup: yes
    - name: Ensure required entries are made to hosts file
      lineinfile:
        path: /etc/exports
        state: present
        backup: yes
        line: '/data/share *(rw,sync,no_root_squash)'
    - name: Re-export the share
      command: exportfs -r

- name: Mount NFS
  hosts: sn06
  become: true
  become_user: root
  tasks:
    - name: Mount network share
      ansible.posix.mount:
        src: "{{ nfs_server_ip }}:/data/share"
        path: /data/share
        fstype: nfs
        state: mounted

- name: Mount NFS on CM
  hosts: central_manager
  become: true
  become_user: root
  tasks:
    - name: Mount network share
      ansible.posix.mount:
        src: "{{ nfs_server_ip }}:/data/share"
        path: /data/share
        fstype: nfs
        state: mounted


###### TO SHARE 2 DIRS
# ---
# - name: Configure NFS server
#   hosts: nfs
#   become: true
#   tasks:
#     - name: Create directories if missing
#       file:
#         path: "{{ item.dir }}"
#         owner: "{{ item.owner }}"
#         group: "{{ item.group }}"
#         mode: "{{ item.mode }}"
#         state: directory
#       with_items:
#         - { dir: /opt/galaxy, mode: "0755", owner: centos, group: centos } 
#         - { dir: /data/share, mode: "0755", owner: centos, group: centos } 
#     - name: Remove old entries in /etc/export
#       lineinfile:
#         path: /etc/exports
#         regexp: '\(rw,sync\)' 
#         state: absent
#         backup: yes
#     - name: Ensure required entries are made to hosts file
#       lineinfile:
#         path: /etc/exports
#         state: present
#         backup: yes
#         line: '{{ item }}'
#       with_items:
#         - '/data/share *(rw,sync,no_root_squash)'
#         - '/opt/galaxy *(rw,sync,no_root_squash)'
#     - name: Re-export the share
#       command: exportfs -r

# - name: Mount NFS
#   hosts: sn06
#   become: true
#   become_user: root
#   tasks:
#     - name: Mount network share
#       ansible.posix.mount:
#         src: "{{ item.src }}"
#         path: "{{ item.mountpoint }}"
#         fstype: nfs
#         state: mounted
#       with_items:
#         - { src: "{{ nfs_server_ip }}:/data/share", mountpoint: /data/share } 
#         - { src: "{{ nfs_server_ip }}:/opt/galaxy", mountpoint: /opt/galaxy }

# - name: Mount NFS on CM
#   hosts: central_manager
#   become: true
#   become_user: root
#   tasks:
#     - name: Mount network share
#       ansible.posix.mount:
#         src: "{{ item.src }}"
#         path: "{{ item.mountpoint }}"
#         fstype: nfs
#         state: mounted
#       with_items:
#         - { src: "{{ nfs_server_ip }}:/data/share", mountpoint: /data/share }
#         - { src: "{{ nfs_server_ip }}:/opt/galaxy", mountpoint: /opt/galaxy }
