---
- name: Replica VM
  hosts: replica_dev
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/db-devyml # DB URL + some postgres stuff
    - group_vars/database.yml  
  pre_tasks:
    - name: install acl and psycopg2 packages
      package:
        name: ["acl", "python3-psycopg2"]
      become: true
  roles:
    - galaxyproject.postgresql
    - role: usegalaxy-it.postgres-replication
      become: true
      vars: 
        replication_role: standby
      when: postgres_replication

  post_tasks:
    - name: Install PostgreSQL contrib package for pgcrypto
      ansible.builtin.dnf:
        name: "postgresql{{ __postgresql_version_dotless }}-contrib"
    - name: Install pgcrypto on Galaxy database
      community.postgresql.postgresql_ext:
        name: pgcrypto
        db: "galaxy"
      become: true
      become_user: postgres
