---
- name: Replica VM
  hosts: replica_prod # <- Inventory entry
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/os.yml
    - secret_group_vars/db-main.yml # <- Inventory entry
    - group_vars/database.yml # <- Inventory entry  
  pre_tasks:
    - name: install acl and psycopg2 packages
      dnf:
        name: '{{ postgresql_dependencies }}'
        state: present
      become: true
  roles:
    - galaxyproject.postgresql
    - role: usegalaxy-it.postgres_replication
      become: true
      vars: 
        replication_role: standby
      when: postgres_replication

  post_tasks:
    - name: Install PostgreSQL contrib package for pgcrypto
      ansible.builtin.dnf:
        name: "postgresql{{ __postgresql_version_dotless }}-contrib"
    - name: Install pgcrypto on Galaxy database
      community.postgresql.postgresql_ext:
        name: pgcrypto
        login_db: "galaxy"
      become: true
      become_user: postgres
