---
# tasks file for usegalaxy_it.system_policy

- name: Configure ACLs
  ansible.builtin.include_tasks: fix_acl.yml
  when: usegalaxy_it_system_policy_acl | bool

- name: Configure SELinux
  ansible.builtin.include_tasks: selinux.yml
  when: usegalaxy_it_system_policy_selinux | bool

    #- name: Change site-packages permissins
    #  ansible.builtin.include_tasks: permissions.yml
    #  when: usegalaxy_it_system_permissions | bool
